name: Build pixshift module

on:
  push:
    paths:
      - 'modules/pixshift/**'
      workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make python3 python3-docutils zip

      - name: Build module
        run: |
          cd modules/pixshift
          make ML_PATH=../../

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pixshift-module
          path: modules/pixshift/build/pixshift.mo
